### ISSUE TITLE
Invalid files names on UNIX based systems

### ISSUE THREAD

**Issue by lapsio** [luispadron/BandLoader#2]
Downloader doesn't use all supported characters in songs / albums names:

Actual result:
https://dl.dropboxusercontent.com/u/44131220/undeletable/z88.png

Expected result:
https://dl.dropboxusercontent.com/u/44131220/undeletable/z89.png

The same happens to album names with / and basically any non-ascii character
http://mumbleetc.com
this guy has LOTS of titles like that ^

also this album:
http://mumbleetc.com/track/feeeeeeeeeeeeeeeeee-eeeeeeeeeeeeeeeeeeeeee

throws error about improperly formatted url

**Comment by luispadron** [comment]
So the URL needs to have album after it. for example http://mumbleetc.com/album/pega-ii-do-e-am, it needs to formatted like this, however I will try to allow single track downloading and see if it works in the next version.

**Comment by lapsio** [comment]
Also those 2 blank names were the same, simply ".mp3" instead of "ｌ ｕ ｃ ｋ ｙ ｓ ｐ ａ ｒ ｋ ｌ ｅ .mp3", "Ƞ Ð Ṿ Ṝ.mp3"  and i couldn't copy album without renaming one of tracks to some temporary name first, quite inconvenient.

Adding track number in front of each file name would:
1. make sorting easier
2. prevent empty, ambiguos names

**Comment by luispadron** [comment]
I see that most of this guys songs are unable to stream, thus unable to download. If you could link me a song you would like to download, that can be streamed I could test and see what I can fix. But just remember if you can't stream it on bandcamp it's impossible to download it. 

Okay, so i just tried downloading this http://mumbleetc.com/album/pega-ii-do-e-am and I see what you mean now. It renames the invalid characters and leaves them blank. I cant really see anyway around this, I'll see what I can figure out.

**Comment by lapsio** [comment]
? I can stream all the albums, well tbh I've downloaded all 2015 albums using your downloader (except singles) just had to rename songs and albums after download. Ambiguos name issue was noticed only on ◭PEGA§II ± DOĞĜE AM◭ album, but invalid naming in plenty of albums because this guy seems to like special chars...

**Comment by luispadron** [comment]
Yah I see that lol, not sure why so many special chars but yep I'll look into it. I just need to figure out a clever way to fix the issue of renaming the special chars, since your OS wont let you name it that. Also the reason the track numbers aren't in the name is because it looks weird if you ever put into Itunes or something, but if you did put it onto itunes right now, the tracks will be in order because the songs get encoded.

**Comment by lapsio** [comment]
unix based OSes allow unicode characters in names i guess and python should allow OS detection. In worst case you can name like this at first and then try to exec command:

$ mv "strippedname.mp3" "ｌ ｕ ｃ ｋ ｙ ｓ ｐ ａ ｒ ｋ ｌ ｅ .mp3"

on UNIX system because it seems to work properly

**Comment by luispadron** [comment]
Ah okay, I haven't tested on UNIX however I know it works on UNIX because I coded for all OS's. If special chars work for UNIX system I'll just check for Windows, expect a fix soon! Thanks for the issue report and help with it.

**Comment by luispadron** [comment]
Just fixed issue, let me know how it works for you.

**Comment by lapsio** [comment]
nope :D
Sorry but actually it's first time I launched it on linux, before I used it on windows virtual machine because i was in rush and didn't want to install PyQT4 on lin. So here's result of launching app on album we were using as example:

```
    Traceback (most recent call last):
      File "main.py", line 142, in begin_download
        self.camp_obj.create_dir()
      File "/home/lapsio/Documents/Projekty/Non-mine/BandLoader/BandLoader/bandloader.py", line 87, in create_dir
        os.makedirs(file_path)
      File "/usr/lib64/python3.4/os.py", line 237, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/home/lapsio\\PEGAII  DOE AM\\'
```

I guess your app tried to make dir "/home/lapsio\PEGAII  DOE AM\" but on UNIX systems (both linux and OS X) another slash is used as separator and "\" is character used as escape sequence for special characters like eg. "*" or "/" in file name (if you want to make file named "A/B" you'd create file "/dir/subdir/A\/B" \ says that next character must be used literally not as regular expression or separator), so ur app is trying to actually make directory "lapsio\PEGAII DOE AM\" in /home which is ofc forbidden because it'd create new user home dir and only root can do that.

Afaik windows also does allow using both "/" and "\" as dir separators so maybe changing to "/" globally would be better idea.

To give better view on unix paths:
/home/lapsio/abc -- file "abc"
/home/lapsio/ab\c -- file "abc"
/home/lapsio/abc\ ddd -- file "abc ddd"
/home/lapsio/abc*\/\ ddd -- file "abc*/ ddd"

If you'll provide path as string "asd\sth" python will add \ before \ automatically because it'll assume you wanted to actually use "\" that's why there are double \ but in the end name will contain only one \

**Comment by lapsio** [comment]
If you'd be interested in testing, i can also test app on OS X because i have one installed on my PC but it should work exactly the same way as on linux.

**Comment by luispadron** [comment]
Ahhhh okay, I had fixed the special character issue but have never been able to test fully on unix. I will definitely try and fix this soon, I have OS X but haven't been able to find a way to install PyQt, if you have any information on that let me know. I keep getting an error because I'm on el capitan

**Comment by lapsio** [comment]
I'd probably get some linux virtual machine. I never used osx that much and when I tried to compile my app for it, there was much more trouble than on lin so i guess vm will be simplier solution for quick fix.

**Comment by luispadron** [comment]
Alright, I'll work on it later tomorrow. I think I might just need to change some strings around. So for example UNIX user 2 slashes for directories? so it would be like home//usrs ? or just home/usrs

**Comment by lapsio** [comment]
///// will be merged into single / anyways because "empty" / are merged, so when I'm writing nodejs scripts I don't even care if there's single / or duplicated, path received by your program can have 2 forms but I don't think you even need to care about it:

absolute path:
/home/lapsio/somepath/  (<- started with / )

relative path
somepath/    (<- without / at the beginning)

second will be resolved by system to working path (typically where your python main.py file is located so eg. /home/lapsio/Apps/BandLoader/somepath) but i don't think it's important because it's handled by system itself what you're more interested in is that:

path can have trailing / (/home/lapsio/) or not (/home/lapsio) and it's the same, that's why merging //// is nice feature because you can absolutely not care if there's trailing / or not because in worst case you'll create /home/lapsio//album name which will also work fine.

There's only one exceptional situation:
if user won't provide ANY path ('' empty string) which as i said should be resolved to working dir BUT if you'll add / to empty string it'll become "/" making it by an accident absolute path and trying to save album in system files what is probably not expected.

So code writing dir should be more or less like that in pseudocode (i don't know python):

```
var fullPath=inputPath;   //path provided by user
if (fullPath!="")  //only if not exceptional case
  fullPath+="/"   //add trailing "/"
fullPath+=albumName;   //add new directory name
os.mkdir(fullPath);
```

**Comment by luispadron** [comment]
Ahhh I see, theres a difference with the slashes in Windows and UNIX, and I didn't account for this. This will be an easy fix, i'll update it tomorrow as I'm busy today, thanks again for the help!

**Comment by lapsio** [comment]
Apart from that issue with slashes, special chars seem to work fine:
https://dl.dropboxusercontent.com/u/44131220/undeletable/s40.png

However albm name still doesn't contain specials. (i like download progressbar in terminal though :D)

**Comment by luispadron** [comment]
Alright, so I haven't been able to test on UNIX since I don't have PyQt on my Mac, (Will try to get it soon, since i want to publish a DMG for this) but, it should work? Also, fixed the special chars not being allowed in album names, or artist names. Let me know if you have any problems.

**Comment by lapsio** [comment]
```
Traceback (most recent call last):
  File "main.py", line 142, in begin_download
    self.camp_obj.create_dir()
  File "/home/lapsio/Documents/Projekty/Non-mine/BandLoader/BandLoader/bandloader.py", line 90, in create_dir
    if not os.path.exists(file_path):
UnboundLocalError: local variable 'file_path' referenced before assignment
```

Now it doesn't work at all :D

**Comment by luispadron** [comment]
lol I know what happened, I totally forgot to check if you were even on Linux, was just checking for mac or windows. Fixing right now

**Comment by lapsio** [comment]
technically Windows is the only non-POSIX OS currently widely used so you could just check if it's windows or anything else because it'll work the same way on BSD, Linux, OS X, Solaris, AIX, HP-UX, Oracle UNIX etc etc.

**Comment by luispadron** [comment]
That's exactly what I did. Changes should be up now, hoping it finally works.

**Comment by lapsio** [comment]
Everything works fine now.Thx

**Comment by luispadron** [comment]
Awesome, thanks a lot for helping me fix this and test on UNIX!

**Comment by lapsio** [comment]
The only thing I'd suggest which is not technical issue but more like opinion, is to rather avoid using custom window backgrounds in osx / linux apps, because whereas on windows totally custom gui in apps is kind of standard and everything looks totally not uniform, on linux and osx apps rather look kind of uniform and match system theme. Actually Qt is "native" KDE graphics lib so like 90% of apps on KDE are based on Qt and they feel like native apps. Applications using custom backgrounds or stuff like that look a bit like poor windows ports, not apps created with those OSs in mind. It's just visual experience ofc but as you could notice from my screen (and pics found in the internet) linux GUI is fully customizable in terms of colors, I'm not sure about OS X but i guess it also is and "raw" Qt perfectly works with user defined UI themes and there's no risk that UI will become illegible with certain UI colors combinations.

https://dl.dropboxusercontent.com/u/44131220/undeletable/z90.png
