### ISSUE TITLE
OS X? 

### ISSUE THREAD

**Issue by SainteCelery** [luispadron/BandLoader#3]
Are you still planning to build a Mac release? thx

**Comment by luispadron** [comment]
I am, I have to get PyQt4 working on my mac and then I'll be compiling a DMG file from it. I tried to get it working a month ago but El Capitan was fairly new and was unable to do so, will try again later tonight and see if I can get this compiled for you.

**Comment by SainteCelery** [comment]
Awesome, thank you, I've been checking back every few months hoping to find it.

**Comment by luispadron** [comment]
Been working on this for the past 3 hours and cannot get it to build, sorry not sure what else to do. I'll look into it more tomorrow but just cant get this thing to compile into a .app file.

**Comment by SainteCelery** [comment]
No worries; better to come back to it with fresh eyes. I appreciate the effort.

**Comment by luispadron** [comment]
If you have homebrew installed I can teach you how to get it work via console, but yeah in terms of executable I'll have to work on it tomorrow.

**Comment by luispadron** [comment]
So I finally got this to work, and have compiled the application into an app file. Download link is in the README file. Let me know if you run into any troubles

**Comment by SainteCelery** [comment]
Sorry to keep bugging you about this, but there seems to be some error code results baked into the executable that are keeping it from properly launching.

**Comment by luispadron** [comment]
no not a problem, need the help testing on different machines. Got it to run on mine, but thats probably because i have all the required packages. Will build again tomorrow after my final and see if i can fix it.

**Comment by Gamerbiomek2** [comment]
not Working on OS Sierra

**Comment by luispadron** [comment]
Hey this program is deprecated and no longer being worked on, sorry!
