### ISSUE TITLE
Band Loader crash

### ISSUE THREAD

**Issue by tylerS0887** [luispadron/BandLoader#4]
Using the latest download of BandLoader I have had no issues until the other day. Now when I attempt to download anything from Bandcamp the entire app just crashes and disappears. I have no idea what happened since the day before. Any help on this issue would be greatly appreciated. Thanks!

**Comment by luispadron** [comment]
They may have changed the way their streaming links work, which would then cause issues.

However, this project is sort of deprecated since I haven't touched it in over a year.
If I have a chance I might be able to take a look at it soon and update.

**Comment by tylerS0887** [comment]
I appreciate it. I actually did find another program that works quite
amazinly but thank you for the timely reply and hope you get a chance to
check it out. Thanks again!

**Comment by cynexyl** [comment]
@tylerS0887 Would you mind sharing a link to that software?
Thanks!

**Comment by tylerS0887** [comment]
https://github.com/Otiel/BandcampDownloader
